experiment:
  name: "NEAT_ISEF_2025_Competition"
  description: "Competition-ready NEAT configuration for ISEF mathematics category"
  author: "ItCodinTime"
  version: "1.0.0"
  date: "2025-08-22"
neat:
  network:
    input_dim: 784
    hidden_dims: [512, 256, 128]
    output_dim: 10
    activation_function: "relu"
    output_activation: "softmax"
    dropout_rate: 0.1
    batch_normalization: true
  agents:
    num_agents: 3
    agent_names: ["Strategist", "Optimizer", "Generalizer"]
    agent_specialization: true
  nash_equilibrium:
    regularization_weight: 0.15
    tolerance: 1e-4
    max_iterations: 200
    computation_method: "iterative_best_response"
    verification_frequency: 10
  game_theory:
    payoff_matrix_type: "competitive"
    utility_function: "cross_entropy_nash"
    temperature_parameter: 1.0
    strategy_regularization: 1e-4
training:
  learning_rate: 0.001
  batch_size: 64
  num_epochs: 1000
  weight_decay: 1e-4
  optimizer:
    type: "adam"
    momentum: 0.9
    beta1: 0.9
    beta2: 0.999
    epsilon: 1e-8
  lr_scheduler:
    type: "cosine_annealing"
    step_size: 100
    gamma: 0.95
    min_lr: 1e-6
  convergence:
    patience: 50
    min_improvement: 1e-5
    max_gradient_norm: 1.0
    nash_convergence_weight: 0.3
evaluation:
  benchmarks:
    enabled: ["MMLU", "MATH", "HumanEval", "StrategyGames"]
    math_reasoning:
      num_problems: 500
      difficulty_levels: ["easy", "medium", "hard", "competition"]
      categories: ["algebra", "geometry", "calculus", "number_theory"]
    strategic_games:
      num_scenarios: 100
      game_types: ["prisoners_dilemma", "coordination", "auction", "bargaining"]
    code_generation:
      num_tasks: 164
      languages: ["python"]
      timeout: 10
  baselines:
    models: ["GPT-4", "GPT-4-Turbo", "Gemini-Pro", "Claude-3-Opus", "Grok-1"]
    api_rate_limit: 60
    retry_attempts: 3
  metrics:
    primary: ["accuracy", "nash_stability", "convergence_rate"]
    secondary: ["training_time", "memory_usage", "robustness_score"]
    statistical_tests: true
    confidence_level: 0.95
data:
  datasets:
    training_split: 0.8
    validation_split: 0.1
    test_split: 0.1
  augmentation:
    enabled: true
    rotation_range: 15
    width_shift_range: 0.1
    height_shift_range: 0.1
    noise_level: 0.01
  synthetic:
    generate_additional: true
    augmentation_factor: 2
    noise_injection: true
hardware:
  device: "auto"
  mixed_precision: true
  distributed_training: false
  data_parallel: true
  num_workers: 4
  pin_memory: true
  benchmark_mode: true
logging:
  level: "INFO"
  log_file: "logs/neat_training.log"
  console_output: true
  metrics_frequency: 10
  save_model_frequency: 100
  plot_frequency: 50
output:
  results_dir: "results/isef_2025"
  create_timestamp_dir: true
  save_config: true
  save_logs: true
  save_plots: true
  save_models: true
  save_benchmarks: true
  generate_report: true
  report_format: ["pdf", "html"]
  include_visualizations: true
  statistical_analysis: true
